//! 메뉴 · 대화상자 글(한국어 / 영어).

pub struct Strings {
    pub file: &'static str,
    pub open: &'static str,
    pub recent: &'static str,
    pub no_recent: &'static str,
    pub clear_recent: &'static str,
    pub reveal: &'static str,
    pub copy_path: &'static str,
    pub print: &'static str,
    pub export_pdf: &'static str,
    pub close: &'static str,
    pub quit: &'static str,
    pub view: &'static str,
    pub toc: &'static str,
    pub find: &'static str,
    pub source: &'static str,
    pub zoom_in: &'static str,
    pub zoom_out: &'static str,
    pub zoom_reset: &'static str,
    pub theme: &'static str,
    pub theme_system: &'static str,
    pub theme_light: &'static str,
    pub theme_dark: &'static str,
    pub remote: &'static str,
    pub keep_warm: &'static str,
    pub autostart: &'static str,
    pub fullscreen: &'static str,
    pub help: &'static str,
    pub set_default: &'static str,
    pub about: &'static str,
    pub licenses: &'static str,
    pub save: &'static str,
    pub edit: &'static str,
    pub copy: &'static str,
    pub select_all: &'static str,
    pub native_view: &'static str,
    pub dlg_save_title: &'static str,
    pub dlg_save: &'static str,
    pub dlg_dont_save: &'static str,
    pub dlg_cancel: &'static str,
    pub dlg_conflict_title: &'static str,
    pub dlg_conflict_body: &'static str,
    pub dlg_overwrite: &'static str,
    pub dlg_encoding_title: &'static str,
    pub dlg_encoding_body: &'static str,
    pub dlg_save_utf8: &'static str,
}

pub static KO: Strings = Strings {
    file: "파일",
    open: "열기…",
    recent: "최근 문서",
    no_recent: "(없음)",
    clear_recent: "목록 지우기",
    reveal: "파일 위치 열기",
    copy_path: "경로 복사",
    print: "인쇄…",
    export_pdf: "PDF로 내보내기…",
    close: "닫기",
    quit: "끝내기",
    view: "보기",
    toc: "목차",
    find: "찾기",
    source: "원문 보기 / 서식 보기",
    zoom_in: "확대",
    zoom_out: "축소",
    zoom_reset: "원래 크기",
    theme: "테마",
    theme_system: "시스템",
    theme_light: "밝게",
    theme_dark: "어둡게",
    remote: "원격 이미지 불러오기",
    keep_warm: "닫은 뒤에도 잠시 준비해 두기 (빠른 시작)",
    autostart: "로그인할 때 미리 켜 두기 (창 없이 대기)",
    fullscreen: "전체 화면",
    help: "도움말",
    set_default: "기본 앱으로 설정…",
    about: "Marklet 정보",
    licenses: "오픈소스 라이선스",
    save: "저장",
    edit: "편집",
    copy: "복사",
    select_all: "모두 선택",
    native_view: "빠른 보기 (네이티브 렌더링)",
    dlg_save_title: "변경 내용을 저장할까요?",
    dlg_save: "저장",
    dlg_dont_save: "저장 안 함",
    dlg_cancel: "취소",
    dlg_conflict_title: "파일이 다른 곳에서 바뀌었습니다",
    dlg_conflict_body: "지금 저장하면 그 변경을 덮어씁니다.",
    dlg_overwrite: "덮어쓰기",
    dlg_encoding_title: "이 인코딩으로 저장할 수 없는 글자가 있습니다",
    dlg_encoding_body:
        "UTF-8 로 저장하면 모든 글자를 보존합니다. 다른 프로그램에서 이 파일을 열 때 한글이 깨질 수 있습니다.",
    dlg_save_utf8: "UTF-8 로 저장",
};

pub static EN: Strings = Strings {
    file: "File",
    open: "Open…",
    recent: "Recent",
    no_recent: "(none)",
    clear_recent: "Clear list",
    reveal: "Show in folder",
    copy_path: "Copy path",
    print: "Print…",
    export_pdf: "Export as PDF…",
    close: "Close",
    quit: "Exit",
    view: "View",
    toc: "Outline",
    find: "Find",
    source: "Show source / rendered",
    zoom_in: "Zoom in",
    zoom_out: "Zoom out",
    zoom_reset: "Actual size",
    theme: "Theme",
    theme_system: "System",
    theme_light: "Light",
    theme_dark: "Dark",
    remote: "Load remote images",
    keep_warm: "Stay ready after closing (fast start)",
    autostart: "Start at sign-in (waits without a window)",
    fullscreen: "Full screen",
    help: "Help",
    set_default: "Set as default app…",
    about: "About Marklet",
    licenses: "Open-source licenses",
    save: "Save",
    edit: "Edit",
    copy: "Copy",
    select_all: "Select all",
    native_view: "Fast view (native renderer)",
    dlg_save_title: "Save changes?",
    dlg_save: "Save",
    dlg_dont_save: "Don't save",
    dlg_cancel: "Cancel",
    dlg_conflict_title: "The file was changed elsewhere",
    dlg_conflict_body: "Saving now will overwrite that change.",
    dlg_overwrite: "Overwrite",
    dlg_encoding_title: "Some characters cannot be saved in this encoding",
    dlg_encoding_body:
        "Saving as UTF-8 keeps every character. Other programs may show garbled text for this file.",
    dlg_save_utf8: "Save as UTF-8",
};

/// 시스템 언어가 한국어면 한국어, 아니면 영어.
pub fn pick(locale: &str) -> &'static Strings {
    if locale.to_ascii_lowercase().starts_with("ko") {
        &KO
    } else {
        &EN
    }
}
